# Generated by Django 2.1.5 on 2020-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='app_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
