# Generated by Django 2.1.5 on 2020-02-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20200212_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardMessageConfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.AppModel')),
            ],
            options={
                'verbose_name': '转发配置表',
                'verbose_name_plural': '转发配置表',
            },
        ),
        migrations.CreateModel(
            name='NoteMessage',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wechat.MessageModel')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '提示消息',
                'verbose_name_plural': '提示消息',
            },
        ),
        migrations.AlterModelOptions(
            name='cardmessage',
            options={'verbose_name': '名片消息', 'verbose_name_plural': '名片消息'},
        ),
    ]
