# Generated by Django 2.1.5 on 2020-02-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20200213_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.AppModel')),
            ],
            options={
                'verbose_name': '转发log表',
                'verbose_name_plural': '转发log表',
            },
        ),
    ]
